// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hazr
NumericVector hazr(double t, double m, double bm, double bt, NumericMatrix dat);
RcppExport SEXP hazr_hazr(SEXP tSEXP, SEXP mSEXP, SEXP bmSEXP, SEXP btSEXP, SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type bm(bmSEXP);
    Rcpp::traits::input_parameter< double >::type bt(btSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dat(datSEXP);
    __result = Rcpp::wrap(hazr(t, m, bm, bt, dat));
    return __result;
END_RCPP
}
// nnhazr
NumericVector nnhazr(double t, double m, double bm, double bt, NumericMatrix dat);
RcppExport SEXP hazr_nnhazr(SEXP tSEXP, SEXP mSEXP, SEXP bmSEXP, SEXP btSEXP, SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type bm(bmSEXP);
    Rcpp::traits::input_parameter< double >::type bt(btSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dat(datSEXP);
    __result = Rcpp::wrap(nnhazr(t, m, bm, bt, dat));
    return __result;
END_RCPP
}
