# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hazr <- function(t, m, bm, bt, dat) {
    .Call('hazr_hazr', PACKAGE = 'hazr', t, m, bm, bt, dat)
}

nnhazr <- function(t, m, bm, bt, dat) {
    .Call('hazr_nnhazr', PACKAGE = 'hazr', t, m, bm, bt, dat)
}

